apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: slack_api_url
      remoteRef:
        key: veille-immo-prod-alertmanager-slack # doit correspondre à ${alertmanager_secret_name} (sortie Terraform)
        property: slack_api_url
