{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "flask-app.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: DATABASE_URL
{{- end }}
