apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yace
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Styyde/flask-gitops---public-veille-immobiliere.git
    targetRevision: main
    path: yace
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
